annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.15'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
  truecharts.org/SCALE-support: 'true'
apiVersion: v2
appVersion: "1.2"
dependencies:
  - name: common
    version: 24.1.10
    repository: https://petersandor.github.io/truecharts-common
    condition: ''
    alias: ''
    tags: []
    import-values: []
deprecated: false
description: An open-source single page application to view your photos in the easiest way possible.
home: https://truecharts.org/charts/stable/pixapop
icon: https://truecharts.org/img/hotlink-ok/chart-icons/pixapop.webp
keywords:
  - pixapop
  - photo
  - gallery
  - image
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: pixapop
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/pixapop
  - https://ghcr.io/linuxserver/pixapop
  - https://github.com/bierdok/pixapop
  - https://github.com/linuxserver/docker-pixapop
type: application
version: 12.1.5
