image:
  repository: collabora/code
  pullPolicy: IfNotPresent
  tag: 24.04.5.2.1@sha256:1582d87ab06f586e7b0b3cee4ca970393b8f3d5597eb2a9d0a4f5861b1b138c1
collabora:
  username: admin
  password: changeme
  interface: default
  dictionaries:
    - de_DE
    - en_GB
    - en_US
    - el_GR
    - es_ES
    - fr_FR
    - pt_BR
    - pt_PT
    - it
    - nl
    - ru
  server_name: example.com
  aliasgroup1: https://cloud.example.com
  ssl_enable: false
  ssl_termination: true
  no_gen_ssl: true
  extra_params:
    - --o:welcome.enable=false
workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
            - configMapRef:
                name: collabora-config
          securityContext:
            runAsUser: 100
            runAsGroup: 102
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - CHOWN
                - FOWNER
                - SYS_CHROOT
                - MKNOD
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9980
        port: 9980
portal:
  open:
    enabled: true
