annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: metrics
  truecharts.org/max_helm_version: '3.15'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
  truecharts.org/SCALE-support: 'true'
apiVersion: v2
appVersion: "3.5.4"
dependencies:
  - name: common
    version: 24.1.10
    repository: https://petersandor.github.io/truecharts-common
    condition: ''
    alias: ''
    tags: []
    import-values: []
deprecated: false
description: Speedtest Exporter made in python using the official speedtest bin
home: https://truecharts.org/charts/stable/speedtest-exporter
icon: https://truecharts.org/img/hotlink-ok/chart-icons/speedtest-exporter.webp
keywords:
  - speedtest-exporter
  - speedtest
  - metrics
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: speedtest-exporter
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/speedtest-exporter
  - https://ghcr.io/miguelndecarvalho/speedtest-exporter
  - https://github.com/MiguelNdeCarvalho/speedtest-exporter/
type: application
version: 12.1.5
