annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.15'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
  truecharts.org/SCALE-support: 'true'
apiVersion: v2
appVersion: "10.9.10"
dependencies:
  - name: common
    version: 24.1.8
    repository: https://petersandor.github.io/truecharts-common
    condition: ''
    alias: ''
    tags: []
    import-values: []
deprecated: false
description: Jellyfin is a Free Software Media System
home: https://truecharts.org/charts/stable/jellyfin
icon: https://truecharts.org/img/hotlink-ok/chart-icons/jellyfin.png
keywords:
  - jellyfin
  - plex
  - emby
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: jellyfin
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/jellyfin
  - https://ghcr.io/jellyfin/jellyfin
  - https://github.com/jellyfin/jellyfin
  - https://hub.docker.com/r/alpine/socat
type: application
version: 20.1.20
