image:
  repository: docker.io/bellamy/wallos
  tag: latest@sha256:9995385e81faeba1b2992a0d59213418a3dcaa45f2f3c321d1a1f9aa513d2456
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8282
        protocol: tcp
        targetPort: 80

persistence:
  database:
    enabled: true
    mountPath: "/var/www/html/db"
  logos:
    enabled: true
    mountPath: "/var/www/html/images/uploads/logos"

portal:
  open:
    enabled: true
