annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: incubator
  truecharts.org/max_helm_version: '3.15'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
  truecharts.org/SCALE-support: 'true'
apiVersion: v2
appVersion: "3.11.2"
dependencies:
  - name: common
    version: 24.1.8
    repository: https://petersandor.github.io/truecharts-common
    condition: ''
    alias: ''
    tags: []
    import-values: []
deprecated: false
description: Ddclient is a Perl client used to update dynamic DNS entries for accounts on Dynamic DNS Network Service Provider.
home: https://truecharts.org/charts/stable/ddclient
icon: https://truecharts.org/img/hotlink-ok/chart-icons/ddclient.png
keywords:
  - ddclient
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: ddclient
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/ddclient
  - https://ghcr.io/linuxserver/ddclient
type: application
version: 11.1.9
