image:
  repository: jenkins/jenkins
  pullPolicy: IfNotPresent
  tag: 2.476-jdk17@sha256:ad2d26b2fa1b4a0f14185a8fc00f1720c5e56870322ce932771f91a0c8c8fe99
security:
  container:
    runAsGroup: 1000
    runAsUser: 1000
  pod:
    fsGroup: 1000
# securityContext:
#   readOnlyRootFilesystem: false
jenkins:
  java_opts: []
  jenkins_opts: []
  jenkins_java_opts: []
  plugins_force_upgrade: false
  upgrade_if_no_marker: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /login
            readiness:
              type: http
              path: /login
            startup:
              type: tcp
          envFrom:
            - secretRef:
                name: "jenkins-secret"
service:
  main:
    ports:
      main:
        protocol: http
        port: 10280
  agent:
    enabled: true
    ports:
      agent:
        enabled: true
        port: 50000
persistence:
  data:
    enabled: true
    mountPath: /var/jenkins_home
portal:
  open:
    enabled: true
